version: '3'
services:
  nodeapp:
    build: .
    container_name: cdp-td5
    ports:
      - 3002:3000
    restart: unless-stopped

  mongodb:
    container_name: mongo
    image: mongo
    ports:
      - 8081:8081
      - 27017:27017
